export const elementIcon = {
    normal : require('../../assets/elementos/normal.png'),
    fire : require('../../assets/elementos/fogo.png'),
    water : require('../../assets/elementos/agua.png'),
    grass : require('../../assets/elementos/grama.png'),
    flying : require('../../assets/elementos/voador.png'),
    fighting : require('../../assets/elementos/lutador.png'),
    poison : require('../../assets/elementos/veneno.png'),
    electric : require('../../assets/elementos/eletrico.png'),
    ground : require('../../assets/elementos/terra.png'),
    rock : require('../../assets/elementos/pedra.png'),
    psychic : require('../../assets/elementos/psiquico.png'),
    ice : require('../../assets/elementos/gelo.png'),
    bug : require('../../assets/elementos/inseto.png'),
    ghost : require('../../assets/elementos/fantasma.png'),
    steel : require('../../assets/elementos/ferro.png'),
    dragon : require('../../assets/elementos/dragao.png'),
    dark : require('../../assets/elementos/sombrio.png'),
    fairy : require('../../assets/elementos/fada.png'),
}